UPDATE SCHOOL_INFO
SET DEP_NAME = N'経済学部'
WHERE SHC_CD = N'1001' AND DEP_NAME = N'商業学部';

UPDATE SCHOOL_INFO
SET DEP_NAME = N'国際学部'
WHERE SHC_CD = N'2001' AND DEP_NAME = N'法学部';

UPDATE SCHOOL_INFO
SET DEP_NAME = N'情報学部'
WHERE SHC_CD = N'4001' AND DEP_NAME = N'社会学部';